Service:
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: deerflow-
    SupplierDeployMetadata:
      ArtifactRelation:
        centos_7:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 新建ECS实例
        Url: 'ros_templates/template-create-ecs.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: deerflow
    Description: deerflow
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: aliyun_3_x64_20G_alibase_20240819.vhd
    SystemDiskSize: 20
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 100
    CommandType: RunShellScript
    Timeout: 10800
    CommandContent: |-
        #!/bin/bash
        yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum makecache
        yum install -y wget curl unzip git jq
        yum install -y docker-ce
        systemctl enable --now docker.socket

        git clone https://github.com/KunSir991/deer-flow.git
        cd deer-flow
        cp conf.yaml.example conf.yaml
        cp .env.example .env
        docker compose up -d --build
